#' remove files associated with pdphmc model
#' 
#' @description remove files associated with model generated by `build` 
#' @examples file.copy(system.file('examples/test_case.cpp', package = "pdphmc"),".")
#' mdl <- pdphmc::build("test_case.cpp")
#' fit <- pdphmc::run(mdl)
#' pdphmc::clean(mdl) # will no longer work as binary is deleted...
#' file.remove("test_case.cpp") #clean up
#' @param model S4 class of type `build-output` typically generated by function `build` 
#' 
#' @export
clean <- function(model){
  file.remove(list.files(model@work.folder,full.names = TRUE))
  file.remove(model@work.folder)
}

